dataset:
  data_dir: mit-states/compcos_dif_val/
  dataset: mit-states
  splitname: mit_split2_tr_object
experiment:
  name: mit_split2_tr_object_tmn
model_params:
  model: tmn
  emb_init: glove
  image_extractor: resnet18
  num_negs: 1
  embed_rank: 64
  emb_dim: 16
  nmods: 24
training:
  batch_size: 256
  eval_val_every: 2
  load: 
  lr: 0.0001
  lrg: 0.01
  margin: 0.5
  max_epochs: 100
  norm_family: imagenet
  save_every: 10000
  test_batch_size: 32
  test_set: val
  topk: 1
  wd: 5.0e-05
  workers: 8
  update_features: false
  freeze_features: false