dataset:
  data_dir: osdd/compcos_generic/
  dataset: osdd
  open_world: true
  splitname: zero_shot_pairs1_generic
experiment:
  name: zero_shot_pairs1_generic
model_params:
  dropout: true
  emb_dim: 600
  emb_init: ft+w2v
  fc_emb: 768,1024,1200
  image_extractor: resnet18
  model: compcos
  nlayers: 2
  norm: true
  relu: false
  static_inp: false
  train_only: false
training:
  batch_size: 128
  cosine_scale: 20
  epoch_max_margin: 15
  freeze_features: false
  load: null
  lr: 5.0e-05
  lrg: 0.001
  margin: 0.4
  max_epochs: 300
  norm_family: imagenet
  save_every: 10000
  test_batch_size: 64
  test_set: val
  topk: 1
  update_features: false
  wd: 5.0e-05
  workers: 8
