---
experiment:
  name: IVR/osdd_ow
dataset:
  data_dir: osdd/compcos_dif_val/
  dataset: osdd
  splitname: zero_shot_split1_tr_cw
model_params:
  nlayers: 2
  emb_dim: 300
  image_extractor: resnet18
training:
  open_wolrd: true
  batch_size: 512
  load:
  lr: 5.0e-05
  lrg: 0.001
  cosine_scale: 20
  max_epochs: 300 
  save_every: 10000
  test_batch_size: 32
  test_set: val
  topk: 1
  wd: 5.0e-05
  workers: 8
  update_features: false
  lambda_rep: 1
  lambda_grad: 10
 

