!!python/object:argparse.Namespace
aow: 1.0
attr: false
auc: false
batch_size: 128
bias: 1000.0
clean_only: false
clf_init: false
code_level: top
code_voc: 512
composition: mlp_add
config: configs/mit_states_ow.yml
config_name: ''
cosine_scale: 50
cpu_eval: false
cv_dir: logs/
data_dir: mit-states/compcos_dif_val/
dataset: mit-states
drop: 0.8333333333333334
drop_out: 0.1
dropout: true
emb_dim: 300
emb_init: word2vec
embed_rank: 64
epoch_max_margin: 100
eval_type: dist
eval_val_every: 1
fc_emb: 768,1024
freeze_features: false
gcn_type: gcn
gpu: 0
gr_emb: d4096,d
graph: false
graph_init: null
hard_masking: false
hm: false
image_extractor: dino
img_feature_dim: 2054
img_feature_type: resnet18
lambda_ant: 0.0
lambda_aux: 0.0
lambda_axiom: 0
lambda_cls_attr: 0
lambda_cls_obj: 0
lambda_comm: 0.0
lambda_inv: 0.0
lambda_sym: 0
lambda_trip: 0
load: null
logpath: null
loss_type: ''
lr: 5.0e-05
lrg: 0.001
margin: 1.0
max_epochs: 300
max_img_seq_length: 1
max_seq_length: 7
model: ade
model_name_or_path: ./data/Oscar_pretrained_models/base-vg-labels/ep_107_1192087
name: mit_split2_tr_ow
nlayers: 2
nmods: 24
norm: true
norm_family: imagenet
num_negs: 1
open_world: true
pair_dropout: 0.0
relu: false
save_every: 10000
seed: 0
splitname: mit_split2_tr_cw
static_inp: false
subset: false
task_name: czsl
test_batch_size: 128
test_set: val
threshold: null
threshold_trials: 50
tokenizer_name: ''
topk: 1
train_only: false
update_feasibility_every: 1
update_features: false
use_layernorm: false
wd: 5.0e-05
workers: 8
