dataset:
  data_dir: vaw_states/compcos_dif_val/
  dataset: vaw_states
  splitname: zero_shot_split1_tr_object
experiment:
  name: vaw_states_object_ow
model_params:
  model: kgsp
  partial: false
  gumbel: false
  kbfile: feasibility_scores/vaw_states_obj_conceptnet.npy
  pseudo: false
  dropout: true
  norm: true
  nlayers:
  fc_emb: 768,1024,1200
  gr_emb: d4096,d
  emb_dim: 512
  emb_init: null
  graph_init: utils/cgqa-graph.t7
  eval_type: otherdist
  image_extractor: resnet18
  train_only: true
  static_inp: false
training:
  batch_size: 256
  eval_val_every: 20
  load:
  lr: 5.0e-05
  wd: 5.0e-05
  lrg: 5.0e-06
  margin: 2
  max_epochs: 80
  norm_family: imagenet
  save_every: 10000
  test_batch_size: 256
  test_set: val
  topk: 1
  workers: 8
  update_features: true
  freeze_featues: false
